# Generated by Django 4.2.17 on 2026-03-03 16:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('starvation_threshold_minutes', models.IntegerField(default=30)),
                ('priority_weight_config', models.JSONField(default=dict)),
                ('profile_type', models.CharField(default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('escalated', 'Escalated'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('triage_stage', models.CharField(choices=[('rapid', 'Rapid'), ('structured', 'Structured')], default='rapid', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('rejection_count', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'encounters',
            },
        ),
        migrations.CreateModel(
            name='HospitalConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=200, unique=True)),
                ('feature_flags', models.JSONField(default=dict)),
                ('avg_revenue_per_patient', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sla_code_blue_seconds', models.IntegerField(default=120)),
                ('sla_trauma_seconds', models.IntegerField(default=300)),
                ('sla_manual_seconds', models.IntegerField(default=900)),
                ('max_active_cases_per_doctor', models.IntegerField(default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospital_config',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('contact_phone', models.TextField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clerk_user_id', models.TextField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('nurse', 'Nurse'), ('doctor', 'Doctor'), ('admin', 'Admin'), ('dept_head', 'Department Head')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('availability_state', models.CharField(choices=[('available', 'Available'), ('in_procedure', 'In Procedure'), ('off_shift', 'Off Shift'), ('emergency', 'Emergency'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('shift_start', models.DateTimeField(blank=True, null=True)),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('last_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.department')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='EscalationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('code_blue', 'Code Blue'), ('trauma_override', 'Trauma Override'), ('manual_escalation', 'Manual Escalation')], max_length=30)),
                ('response_time', models.IntegerField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('sla_breached', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_escalations', to='core.user')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalation_events', to='core.encounter')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_escalations', to='core.user')),
            ],
            options={
                'db_table': 'escalationevent',
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_encounters', to='core.user'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='core.department'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='core.patient'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('pre_change_snapshot', models.JSONField(blank=True, null=True)),
                ('post_change_snapshot', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.user')),
            ],
            options={
                'db_table': 'auditlog',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('avg_wait_time', models.FloatField(null=True)),
                ('starvation_count', models.IntegerField(default=0)),
                ('escalation_count', models.IntegerField(default=0)),
                ('throughput', models.IntegerField(default=0)),
                ('doctor_utilization_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='core.department')),
            ],
            options={
                'db_table': 'analyticssnapshot',
            },
        ),
        migrations.CreateModel(
            name='AllocationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True)),
                ('accepted', models.BooleanField(null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_logs', to='core.encounter')),
                ('from_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_from', to='core.user')),
                ('to_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_to', to='core.user')),
            ],
            options={
                'db_table': 'allocationlog',
            },
        ),
        migrations.CreateModel(
            name='TriageData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vitals_json', models.JSONField(blank=True, null=True)),
                ('symptoms_json', models.JSONField(blank=True, null=True)),
                ('red_flag_json', models.JSONField(blank=True, null=True)),
                ('raw_input_text', models.TextField(blank=True, null=True)),
                ('llm_processed_json', models.JSONField(blank=True, null=True)),
                ('data_completeness_ratio', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_data', to='core.encounter')),
            ],
            options={
                'db_table': 'triagedata',
                'indexes': [models.Index(fields=['encounter'], name='triagedata_encount_10a4ab_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['department', 'status'], name='encounters_departm_00058e_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['priority', 'created_at'], name='encounters_priorit_c698b9_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['department', 'status', 'priority', 'created_at'], name='encounters_departm_6f5a40_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id', 'timestamp'], name='auditlog_entity__3db843_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['date', 'department'], name='analyticssn_date_2ba45d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticssnapshot',
            unique_together={('date', 'department')},
        ),
        migrations.AddIndex(
            model_name='allocationlog',
            index=models.Index(fields=['encounter', 'timestamp'], name='allocationl_encount_f82d12_idx'),
        ),
    ]
