# Generated by Django 4.2.17 on 2026-03-04 09:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_password_hash_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('media_json', models.JSONField(default=list)),
                ('report_text', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='core.user')),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='core.encounter')),
            ],
            options={
                'db_table': 'assessment',
            },
        ),
    ]
