# Generated by Django 4.2.17 on 2026-03-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assessment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='bed_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
