# Generated by Django 4.2.17 on 2026-03-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_encounter_ambulance_insight_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='ai_insight_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='eta_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='eta_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
