# Generated by Django 4.2.17 on 2026-03-05 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_encounter_ai_insight_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='code_blue_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='encounter',
            name='code_blue_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='code_blue_acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_blue_acks', to='core.user'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='code_blue_active',
            field=models.BooleanField(default=False),
        ),
    ]
