# Generated by Django 4.2.17 on 2026-04-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_code_blue_persistence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clerk_user_id',
        ),
    ]
