# Generated by Django 4.2.17 on 2026-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_clerk_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='status',
            field=models.CharField(choices=[('incoming', 'Incoming Ambulance'), ('waiting', 'Waiting'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('admitted', 'Admitted'), ('completed', 'Completed'), ('escalated', 'Escalated'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
